services:

    web:

      build:
        args:
          build_env: production
        context: .
        target: production

      environment:
        SCRIPT_NAME: /blog_app
        FLASK_APP: blog_app
        FLASK_ENV: production

      volumes:
        - stream:/tmp/blog_app

    postgres:

      image: postgres

      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: blog-application

      volumes:
        - psql_data:/var/lib/postgresql/data

    # pgadmin:
    #
    #   image: dpage/pgadmin4
    #
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: self@pg.admin
    #     PGADMIN_DEFAULT_PASSWORD: pgadmin
    #
    #   ports:
    #     - 5021:80

volumes:
  stream:
  psql_data:
