services:

    web:

      build:
        args:
          - build_env=production
        context: .
        target: production

      env_file:
        - secrets.env

      environment:
        # app mount path relative to host
        SCRIPT_NAME: /blog_app
        # Flask config
        FLASK_APP: blog_app
        FLASK_ENV: production
        # database config override if needed
        # POSTGRES_USER: postgres
        # POSTGRES_PASSWORD: postgres
        # POSTGRES_HOST: postgres
        # POSTGRES_PORT: 5432
        # POSTGRES_DB: blog-application

      ports:
        - 8000:8000

    postgres:

      image: postgres

      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: blog-application

      volumes:
        - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
