name: Build

on:
  workflow_dispatch:

jobs:

  build_and_push:

    name: Build & push
    runs-on: ubuntu-latest

    steps:

      - name: Get current latest image id
        run: >
          curl
          -H 'Authorization: token ${GHCR_PAT}'
          -H 'Accept: application/vnd.github.v3+json'
          https://api.github.com/user/packages/container/blog-application/versions |
          python3
          -c "import sys, json; print(json.load(sys.stdin)[0]['id'])"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Allow scripts to be executed
        run: chmod -R +x scripts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Append downcase repo path to the environment
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build image & push to GHCR
        uses: docker/build-push-action@v2
        with:
          build-args:
            -build_env=production
          context: .
          target: production
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
