name: Debug

on:

  workflow_run:
    workflows: ['Test']
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:

  debug:

    name: Debug
    if: ${{ (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub context
        run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}