name: temp

on:
  workflow_dispatch:

jobs:

  temp:

    name: temp
    runs-on: ubuntu-latest

    steps:

      - name: dump github context
        run: echo ${GITHUB_CONTEXT}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
