name: temp

on:
  workflow_dispatch:

jobs:

  temp:

    name: temp
    runs-on: ubuntu-latest

    steps:

      - name: Get current latest image id
        run: >
          wget
          --header="Authorization: token ${GHCR_PAT}"
          --header="Accept: application/vnd.github.v3+json"
          -nv
          -O - https://api.github.com/user/packages/container/blog-application/versions |
          python3 -c "import sys, json; print(json.load(sys.stdin)[0]['id'])"
