name: Test

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog-application
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      FLASK_APP: blog_application
      FLASK_ENV: testing

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up configuration
      run: mv config.py.example config.py

    - name: Install dependencies
      run: >-
        pip install
        -r requirements.txt
        -r tests/requirements.txt

    - name: Lint with flake8
      run: |
        flake8 blog_application --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 blog_application --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest --cov
