name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  run_tests:

    name: Run tests
    runs-on: ubuntu-latest
    container: python
    env:
      FLASK_APP: blog_app
      FLASK_ENV: testing

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog-application
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pipenv
        mkdir .venv
        pipenv install --dev --skip-lock

    - name: Set app configuration
      run: bash -c 'while read -r line; do [[ ! ${line} =~ ^\#.*$ ]] && echo ${line} >> ${GITHUB_ENV}; done < example.env'

    - name: Lint with flake8
      run: |
        pipenv run flake8 blog_app --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 blog_app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pipenv run pytest --cov --cov-report xml:coverage.xml

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
